[hk4e]
dispatch_http_port = 8080 # dispatch的http端口
dispatch_url = "https://hk4e.flswld.com/query_cur_region" # 二级dispatch地址 将域名改为dispatch的外网地址
login_sdk_account_key = "" # sdk服务器账号验证的签名密钥
sdk_env = 2 # sdk环境 0:国内 1:国内沙箱 2:海外

[logger]
level = "debug"
track_line = true
track_thread = true

[database]
url = "mongodb://mongo:27017"

[redis]
addr = "redis://redis:6379"
password = ""

[mq]
nats_url = "nats://nats:4222"
